name: "Test NixOS Dotfiles"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [NixOS]

jobs:
  test-nixos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/determinate-nix-action@v3
        with:
          extra-conf: |
            system-features = nixos-test benchmark big-parallel kvm

      - name: Test flake check
        run: nix flake check

      - name: Test system build
        run: nix build .#nixosConfigurations.devbox.config.system.build.toplevel

      - name: Test home-manager build
        run: nix build .#homeConfigurations."c0d3h01@devbox".activationPackage
