name: Flake CI - checks, inputs

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@v20
      - uses: DeterminateSystems/flake-checker-action@v2
        with:
          check-owner: true
          ignore-missing-flake-lock: false
          fail-mode: true

      - name: Check Flake
        run: nix flake check --all-systems --show-trace
